version: '2.0'

services:

  nginx:
    container_name: wl_frontend
    ports:
    - "127.0.0.1:80:80"
    environment:
    - TZ="Europe/Bucharest"

  php71:
    container_name: wl_php
    volumes:
      - /home/cristiroma/.ssh/id_rsa:/root/.ssh/id_rsa

  solr6:
    container_name: wl_solr6

  db:
    container_name: wl_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
