version: '2.0'

services:

  nginx:
    image: nginx:1.13
    depends_on:
      - php71
    volumes:
      - .docker/conf-nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
      - .docker/conf-nginx/project.conf:/etc/nginx/conf.d/project.conf:ro
      - ./web:/var/www/html/web:z

  php71:
    image: eaudeweb/php-fpm:7.1-1.0.2
    depends_on:
      - db

  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: "drupal"
    volumes:
      - .docker/conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf
      - mysql-data:/var/lib/mysql

  solr6:
    image: library/solr:6.6
    volumes:
      - .docker/conf-solr/core-template:/core-template:ro
      - solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /core-template

volumes:
  mysql-data:
  solr-data:
