version: '2.0'

services:

  nginx:
    container_name: wl_frontend
    ports:
      - "127.0.0.1:80:80"
    environment:
      - TZ="Europe/Bucharest"
    volumes:
      - .:/var/www/html:ro

  php71:
    container_name: wl_php
    volumes:
      - .:/var/www/html:z

  solr6:
    container_name: wl_solr6

  db:
    container_name: wl_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
