---
- name: load vault variables
  include_vars: ../defaults/main_vault.yml

- name: install required system packages
  yum: name="{{ item }}" state="installed"
  with_items: [
    "MySQL-python", "git", "wget",
    "httpd", "mariadb", "mariadb-server",
    "php55w", "php55w-cli", "php55w-gd", "php55w-mbstring", "php55w-mysql", "php55w-xml"
  ]

- name: create system accounts
  user: name="{{ item.username }}" comment="{{ item.comment|default('Created by Ansible deployment') }}"
    group="{{ item.group }}" groups="{{ item.groups }}"
    append="{{ item.append }}" shell="{{ item.shell|default('/bin/bash') }}"
    state="{{ item.state|default('present') }}"
  with_items:
    - { username: "php", group: "apache", groups: "users", append: "yes", password: "{{ user_php_hash }}" }
  tags:
    - create_system_users

- name: install solr server & create wildlex core
  include_role:
    name: base-role-drupal-solr
  vars:
    drupal_solr4_cores: [ "wildlex" ]

- name: install drush command line
  include_role:
    name: base-role-drush

- name: ensure MariaDB is started
  service: name="mariadb" state="started"

- name: create mysql account
  mysql_user: name="{{ wildlex_db_user }}" password="{{ wildlex_db_password }}" priv="{{ wildlex_db_name }}.*:ALL"
    login_user="root" login_password="{{ ecolex_db_root_password }}"
    host="localhost" state="present" update_password="always"

- name: copy mysql database
  copy: src="files/wildlex-latest.sql.bz2" dest="/tmp"

- name: load mysql database
  mysql_db: name="{{ wildlex_db_name }}" state="import" target="/tmp/wildlex-latest.sql.bz2" login_user="root" login_password="{{ ecolex_db_root_password }}"

- name: clone code repo
  git: dest="{{ wildlex_project_home}}" repo="{{ wildlex_project_repository }}" version="master"

- name: create public files directory and set permissions
  file: owner="php" group="apache" path="{{ wildlex_project_home }}/docroot/sites/default/files" state="directory" mode="2770"

- name: unpack public-files.tar.gz
  unarchive: src="files/public-files.tar.gz" dest="{{ wildlex_project_home }}/docroot/sites/default/files" owner="php" group="apache"
    creates="{{ wildlex_project_home }}/docroot/sites/default/files/field_files"

- name: set filesystem permissions
  file: owner="{{ item.owner }}" group="{{ item.group }}" recurse="{{ item.recurse }}" path="{{ item.path }}" state="{{ item.state }}"
  with_items:
    - { owner: "php" , group: "apache" , recurse: "yes" , path: "{{ wildlex_project_home }}" , state: "directory" }
    - { owner: "php" , group: "apache" , recurse: "no"  , path: "{{ wildlex_project_home }}/docroot/.htaccess" , state: "file" }
    - { owner: "php" , group: "apache" , recurse: "yes" , path: "{{ wildlex_project_home }}/docroot/sites/default/files" , state: "directory", mode: "770" }

- name: create settings.php
  template: src="templates/settings.local.php.j2" dest="{{ wildlex_project_home }}/docroot/sites/default/settings.local.php" owner="root" group="root"

- name: create virtual hosts
  template: src="templates/{{ item.template }}" dest="/etc/httpd/conf.d/{{ item.dest }}" owner="root" group="root"
  with_items: "{{ apache_virtual_hosts }}"
  notify: reload httpd server

# - name: configure httpd caching
#  template: src="templates/expires.conf.j2" dest="/etc/httpd/conf.d/expires.conf" owner="root" group="root"
