galaxy_info:
  author: Cristian Romanescu
  description: drush install from repo
  company: Eau de Web
  license: BSD
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - drush
    - drupal
dependencies: []
